// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ntPmZiFfXudDvKnUA0vDU-xOy5bIn-w',
    appId: '1:62052798470:ios:ead8576d9b153416647387',
    messagingSenderId: '62052798470',
    projectId: 'flutterchatapp-2d0c6',
    // databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    // storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    // androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    // iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'com.example.flutterTraining',
  );
}
